server:
  port : 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}/builder?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
